sudo: required
services:
  - docker
language: java
env:
  global:
    - DOCKER_VERSION=1.11.2-0~trusty
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker version
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d -p 27017:27017 mongo:latest
script:
  - "./gradlew check"
after_success:
  - docker push sdkman/sdkman-broker:1.0.0-SNAPSHOT
cache:
  directories:
  - "$HOME/.gradle"
