sudo: required
services:
  - docker
language: java
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d --net=host mongo:latest
script:
  - docker build -t sdkman/sdkman-broker:1.2.1 .
  - docker run -d --env="RATPACK_MONGO__HOST=localhost" --net=host sdkman/sdkman-broker:1.2.1
  - "./gradlew check --stacktrace"
after_success:
  - docker push sdkman/sdkman-broker:1.2.1
cache:
  directories:
  - "$HOME/.gradle"
# blacklist
branches:
  except:
    - RELEASE

