sudo: required
services:
  - docker
language: java
env:
  global:
    - DOCKER_VERSION=1.11.2-0~trusty
before_install:
  - sudo apt-get remove --purge docker-engine
  - sudo apt-get install docker-engine=${DOCKER_VERSION}
  - docker version
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - "./gradlew check --stacktrace"
after_success:
  - docker push sdkman/sdkman-broker:1.0.0-SNAPSHOT
cache:
  directories:
  - "$HOME/.gradle"
# blacklist
branches:
  except:
    - RELEASE

